### ISSUE TITLE
Move repository to traverson org

### ISSUE THREAD

**Issue by basti1302** [traverson/traverson-traversal#1]
As discussed via email - if you want to move these repo to the [traverson GitHub org](https://github.com/traverson), this are the steps to follow:

* Go to https://github.com/punkstarman/traverson-traversal
* Click on Settings (upper right corner)
* Scroll down to the section titled "Danger Zone"
* Click "Transfer"
* Enter `traverson-traversal` in the first input field and `traverson` in the second

**Comment by basti1302** [comment]
Btw, I linked to this project in Traverson's user guide, see https://github.com/traverson/traverson/blob/master/user-guide.markdown#traverson-web-component. Maybe this helps to give this project more attention :)

**Comment by punkstarman** [comment]
Thankyou.

I tried your instructions for transferring but I was unable to complete the process. I got the following error message:

> You don’t have the permission to create repositories on traverson

**Comment by punkstarman** [comment]
OK, I hadn't seen your invite to the traverson org.
